### ISSUE TITLE
Connection could not be established

### ISSUE THREAD

**Issue by keoShine** [carvelli/PalacePal#4]
Not sure if I just did something wrong, but I installed Palace Pal just today, and I can't seem to get traps/chests found by other players to show up.. The "Test Connection" button just sits on "Testing..." endlessly.. The only thing being written to Dalamud.log is that Palace Pal is connected to Splatoon successfully, so there's no indication of what's causing the community findings connection to stall.. Traps and Hoard Coffers discovered by my own pomanders display properly, but nothing from other players is displayed as config window indicates they should be..

**Comment by keoShine** [comment]
Connection issue has resolved itself a few days later.. Connection now establishes when pressing "Test Connection", and community findings are displayed correctly..

**Comment by keoShine** [comment]
Re-opening with relevant error message now that v1.17 has added error log messages when connecting:
```
2022-11-24 10:08:42.537 -05:00 [ERR] [Palace Pal] Could not establish remote connection
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.WaitForStateChangedAsyncCore(StateWatcher watcher)
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.ConnectAsync(Boolean waitForReady, CancellationToken cancellationToken)
   at Pal.Client.RemoteApi.TryConnect(CancellationToken cancellationToken, Boolean retry)
   at Pal.Client.RemoteApi.VerifyConnection(CancellationToken cancellationToken)
   at Pal.Client.Windows.ConfigWindow.<Draw>b__13_0()
```
Full log file is attached..
[dalamud.log](https://github.com/carvelli/PalacePal/files/10085622/dalamud.log)

**Comment by carvelli** [comment]
Hi,

it is likely to be a DNS issue (in which case the grpc client keeps trying to connect, and ignores the `ConnectTimeout` specified - running into the more general `A task was canceled`); could you try updating to 1.18 and checking the dalamud.log again?

I suspect you'll see a few of the following: 
```
[DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:443.
System.Net.Sockets.SocketException (11001): No such host is known.
   at ...
```

In which case, could you please check what the output of `nslookup pal.xn--xxa.tv` is?

**Comment by keoShine** [comment]
Updated to v1.18, and I get the following error now:
```
2022-11-24 17:46:59.484 -05:00 [INF] [Palace Pal] TryConnect: Creating new gRPC channel
2022-11-24 17:46:59.500 -05:00 [DBG] [Palace Pal] Using client certificate 30BA454A091562829FC7BBF45F870D221E6D2E36
2022-11-24 17:46:59.501 -05:00 [INF] [Palace Pal] TryConnect: Connecting to upstream service at https://pal.μ.tv
2022-11-24 17:46:59.501 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' created with addresses: pal.μ.tv:443
2022-11-24 17:46:59.501 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-24 17:46:59.501 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
2022-11-24 17:46:59.501 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to Connecting.
2022-11-24 17:46:59.501 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' connection requested in non-idle state of Connecting.
2022-11-24 17:47:04.514 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:443.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-24 17:47:04.514 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to TransientFailure. Detail: 'Error connecting to subchannel.'.
System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal
.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
```
And the results of `nslookup pal.xn--xxa.tv`:
![image](https://user-images.githubusercontent.com/32491958/203871720-31c49568-e3aa-4c29-b6bc-4e39784a951e.png)

[dalamud.log](https://github.com/carvelli/PalacePal/files/10087608/dalamud.log)

**Comment by carvelli** [comment]
That just sounds like you're running into the connection timeout, which admittedly is only 5 seconds - but then it's also based around the assumption that the whole step from `Creating new gRPC channel` to `state changed to Ready` on my machine takes 100 ms.

You can try the following build with increased connection timeout to see if it fixes the issue: 
[latest.zip](https://github.com/carvelli/PalacePal/files/10087679/latest.zip)

- uninstall palace pal via the plugin installer
- go to settings -> experimental -> scroll to `dev plugin locations at the bottom` and add the path to the extracted `Palace Pal.dll`
- save
- in the plugin installer, under dev tools, install `Palace Pal (dev plugin)`

**Comment by keoShine** [comment]
Still getting a timeout error with a 20s timeout.. Log: [dalamud.log](https://github.com/carvelli/PalacePal/files/10087794/dalamud.log)

```
2022-11-24 19:35:58.005 -05:00 [INF] [Palace Pal] TryConnect: Creating new gRPC channel
2022-11-24 19:35:58.021 -05:00 [DBG] [Palace Pal] Using client certificate 30BA454A091562829FC7BBF45F870D221E6D2E36
2022-11-24 19:35:58.029 -05:00 [INF] [Palace Pal] TryConnect: Connecting to upstream service at https://pal.μ.tv
2022-11-24 19:35:58.034 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' created with addresses: pal.μ.tv:443
2022-11-24 19:35:58.036 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-24 19:35:58.040 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
2022-11-24 19:35:58.042 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to Connecting.
2022-11-24 19:35:58.046 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' connection requested in non-idle state of Connecting.
2022-11-24 19:36:19.390 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:443.
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-24 19:36:19.392 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to TransientFailure. Detail: 'Error connecting to subchannel.'.
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-24 19:36:19.392 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to TransientFailure.
2022-11-24 19:36:19.392 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-24 19:36:20.593 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to Connecting. Detail: 'Connecting to socket.'.
2022-11-24 19:36:20.594 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to Connecting.
2022-11-24 19:36:20.594 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-24 19:36:23.043 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:443.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-24 19:36:23.043 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to TransientFailure. Detail: 'Error connecting to subchannel.'.
System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
2022-11-24 19:36:23.044 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to TransientFailure.
2022-11-24 19:36:23.044 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
```

**Comment by carvelli** [comment]
Sounds like it's a HTTP/2 and/or firewall issue on your end. 

Could you check whether the connection works with the following build? [latest.zip](https://github.com/carvelli/PalacePal/files/10091148/latest.zip)

**Comment by keoShine** [comment]
Still the same error.. I've also checked to verify that I have firewall disabled.. [dalamud.log](https://github.com/carvelli/PalacePal/files/10093343/dalamud.log)
```
2022-11-25 09:00:14.465 -05:00 [DBG] [Palace Pal] Disposing gRPC channel
2022-11-25 09:00:14.465 -05:00 [INF] [Palace Pal] TryConnect: Creating new gRPC channel
2022-11-25 09:00:14.482 -05:00 [DBG] [Palace Pal] Using client certificate 30BA454A091562829FC7BBF45F870D221E6D2E36
2022-11-25 09:00:14.482 -05:00 [INF] [Palace Pal] TryConnect: Connecting to upstream service at https://pal.μ.tv:8443
2022-11-25 09:00:14.482 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' created with addresses: pal.μ.tv:8443
2022-11-25 09:00:14.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-25 09:00:14.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
2022-11-25 09:00:14.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to Connecting.
2022-11-25 09:00:14.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' connection requested in non-idle state of Connecting.
2022-11-25 09:00:35.599 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:8443.
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-25 09:00:35.599 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to TransientFailure. Detail: 'Error connecting to subchannel.'.
System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-25 09:00:35.599 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to TransientFailure.
2022-11-25 09:00:35.599 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-25 09:00:36.450 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to Connecting. Detail: 'Connecting to socket.'.
2022-11-25 09:00:36.450 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to Connecting.
2022-11-25 09:00:36.450 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-25 09:00:39.482 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport] Subchannel id '1' error connecting to socket pal.μ.tv:8443.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
2022-11-25 09:00:39.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Subchannel] Subchannel id '1' state changed to TransientFailure. Detail: 'Error connecting to subchannel.'.
System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
2022-11-25 09:00:39.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel state updated to TransientFailure.
2022-11-25 09:00:39.483 -05:00 [DBG] [Palace Pal] gRPC[Grpc.Net.Client.Balancer.Internal.ConnectionManager] Channel picker updated.
2022-11-25 09:01:14.466 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0xMS0yNVQwOTowMToxNC40NjY3NzE0LTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5UaHJlYWRpbmcuVGFza3MuVGFza0NhbmNlbGVkRXhjZXB0aW9uOiBBIHRhc2sgd2FzIGNhbmNlbGVkLlxyXG4gICBhdCBHcnBjLk5ldC5DbGllbnQuQmFsYW5jZXIuSW50ZXJuYWwuQ29ubmVjdGlvbk1hbmFnZXIuV2FpdEZvclN0YXRlQ2hhbmdlZEFzeW5jQ29yZShTdGF0ZVdhdGNoZXIgd2F0Y2hlcilcclxuICAgYXQgR3JwYy5OZXQuQ2xpZW50LkJhbGFuY2VyLkludGVybmFsLkNvbm5lY3Rpb25NYW5hZ2VyLkNvbm5lY3RBc3luYyhCb29sZWFuIHdhaXRGb3JSZWFkeSwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFBhbC5DbGllbnQuTmV0LlJlbW90ZUFwaS5UcnlDb25uZWN0KENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuLCBJTG9nZ2VyRmFjdG9yeSBsb2dnZXJGYWN0b3J5LCBCb29sZWFuIHJldHJ5KVxyXG4gICBhdCBQYWwuQ2xpZW50Lk5ldC5SZW1vdGVBcGkuVmVyaWZ5Q29ubmVjdGlvbihDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgUGFsLkNsaWVudC5XaW5kb3dzLkNvbmZpZ1dpbmRvdy48VGVzdENvbm5lY3Rpb24+Yl9fMTdfMCgpIiwiQ29udGV4dCI6IltQYWxhY2UgUGFsXSBDb3VsZCBub3QgZXN0YWJsaXNoIHJlbW90ZSBjb25uZWN0aW9uIn0=
2022-11-25 09:01:14.466 -05:00 [ERR] [Palace Pal] Could not establish remote connection
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.WaitForStateChangedAsyncCore(StateWatcher watcher)
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.ConnectAsync(Boolean waitForReady, CancellationToken cancellationToken)
   at Pal.Client.Net.RemoteApi.TryConnect(CancellationToken cancellationToken, ILoggerFactory loggerFactory, Boolean retry)
   at Pal.Client.Net.RemoteApi.VerifyConnection(CancellationToken cancellationToken)
   at Pal.Client.Windows.ConfigWindow.<TestConnection>b__17_0()
```

**Comment by carvelli** [comment]
I've no idea how to solve this then, unfortunately. I didn't see any connection attempts/errors on the server side either.

I also have no idea why it worked at one time randomly unless you were somewhere else/using some other internet connection or some such; there's been no change that would impact it.

There's at least a vaguely planned import feature at some point that would show community markers even if you aren't connected, but there's no timeline when that will happen.

**Comment by keoShine** [comment]
I've tried even running my VPN to see if it would make a difference, and still nothing.. Closing the issue for now since it doesn't seem like any progress will be made, and I'll just keep an eye on updates and see if anything clears up eventually on its own since it does seem like the issue is probs on my end..

**Comment by carvelli** [comment]
Hi,

it's been a while, and I don't know if you're still using the plugin (and/or still having connection problems) - but if you are, there's now a (experimental) way to import markers even if you can't connect to the server. 

- Download v1.25
- Open `%appdata%\XIVLauncher\pluginConfigs\Palace Pal.json`, search for `"BetaKey": ""` and replace it with `"BetaKey": "import"`
- Reload the plugin
- Download https://github.com/carvelli/PalacePal/releases/download/v1.25/export-2022-12-22.pal
- Open the config menu -> import tab, and select the downloaded file

That should (if it's working correctly) give you a baseline of traps/hoard coffers to work with, even if the server can't be reached.

**Comment by keoShine** [comment]
The import works correctly.. Hella figures that I hopped on last night for UCoB, tried connecting on a whim and _succeeded_ somehow, and then tried again today and it's back to failing to connect, so the import feature is extremely appreciated..
